# Generated by Django 4.2.6 on 2023-10-20 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_comment_re_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='re_comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='org_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re_comments', to='movies.comment'),
        ),
    ]
