# Generated by Django 3.2.9 on 2023-09-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
