# Generated by Django 4.2.5 on 2023-09-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='summary',
            field=models.CharField(max_length=20),
        ),
    ]
