# Generated by Django 3.2.9 on 2023-09-26 01:51

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0002_memo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='images'),
        ),
    ]
