WITH UD AS (
    SELECT COUNT(*) AS CNT, YEAR(JOINED) AS YEAR 
    FROM USER_INFO
    GROUP BY YEAR
    HAVING YEAR = 2021
)

SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, COUNT(DISTINCT USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT USER_ID) / UD.CNT, 1) AS PUCHASED_RATIO 
FROM ONLINE_SALE, UD
WHERE USER_ID IN (
    SELECT USER_ID FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH