SELECT FLAVOR
FROM (
    SELECT A.FLAVOR, A.FH_ORDER + B.JUL_ORDER AS TOTAL_ORDER
    FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS FH_ORDER FROM FIRST_HALF GROUP BY FLAVOR) A JOIN
    (SELECT FLAVOR, SUM(TOTAL_ORDER) AS JUL_ORDER FROM JULY GROUP BY FLAVOR) B ON A.FLAVOR = B.FLAVOR
) C
ORDER BY TOTAL_ORDER DESC
LIMIT 3