SELECT A.DEPT_ID, B.DEPT_NAME_EN, A.AVG_SAL
FROM (SELECT ROUND(AVG(SAL)) AS AVG_SAL, DEPT_ID FROM HR_EMPLOYEES
GROUP BY DEPT_ID) A JOIN HR_DEPARTMENT B
ON A.DEPT_ID = B.DEPT_ID
ORDER BY A.AVG_SAL DESC