SELECT A.CART_ID
FROM (
    SELECT DISTINCT CART_ID FROM CART_PRODUCTS 
    WHERE NAME='Milk'
) A JOIN (
    SELECT DISTINCT CART_ID FROM CART_PRODUCTS
    WHERE NAME='Yogurt'
) B ON A.CART_ID = B.CART_ID
ORDER BY CART_ID