WITH FE AS (
    SELECT SUM(CODE) AS SKILL_CODE FROM SKILLCODES
    GROUP BY CATEGORY
    HAVING CATEGORY = 'Front End'
)

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS, FE
WHERE DEVELOPERS.SKILL_CODE & FE.SKILL_CODE
ORDER BY ID