WITH RECURSIVE TIME AS (
    (SELECT 0 HOUR)
    UNION
    (SELECT HOUR+1 FROM TIME WHERE HOUR < 23)
)

SELECT TIME.HOUR, IFNULL(A.COUNT, 0) AS COUNT
FROM TIME LEFT JOIN (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR
    ORDER BY HOUR
) A ON TIME.HOUR = A.HOUR