SELECT A.ANIMAL_ID, A.NAME FROM ANIMAL_INS A LEFT JOIN (
    SELECT ANIMAL_ID, DATETIME AS ADOPTED_DATE FROM ANIMAL_OUTS
) B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE ADOPTED_DATE < DATETIME
ORDER BY DATETIME